
import jsPDF from "jspdf";
import { formatCurrency } from "@/utils/currency";

/**
 * Export a service record and its grouped services as a PDF
 * @param service The full service record object (with vehicle/client info)
 * @param parsedServices Array of { serviceType, items } describing grouped service items
 * @param totalCost Calculated total cost (number)
 * @param nextOilChangeMileage String for next oil change mileage (if any)
 * @param plainNotes Plain technician notes, with no JSON prefix
 */
export function exportServiceRecordToPDF(
  service: any,
  parsedServices: { serviceType: { value: string }, items: any[] }[],
  totalCost: number,
  nextOilChangeMileage: string,
  plainNotes: string
) {
  const doc = new jsPDF();

  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Service Record", 105, y, { align: "center" });

  y += 12;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  // Vehicle/Client
  doc.text("Vehicle:", 15, y); 
  doc.text(
    service.vehicle
      ? `${service.vehicle.year} ${service.vehicle.make} ${service.vehicle.model}`
      : "—",
    45, y
  );
  y += 8;
  doc.text("License Plate:", 15, y);
  doc.text(service.vehicle?.license_plate || "—", 45, y);
  y += 8;
  doc.text("Client:", 15, y);
  doc.text(service.client?.full_name || "—", 45, y);
  if (service.client?.phone) {
    y += 8;
    doc.text("Phone:", 15, y);
    doc.text(service.client.phone, 45, y);
  }
  y += 8;
  doc.text("Status:", 15, y);
  doc.text(service.status, 45, y);

  // Service Details
  y += 12;
  doc.setFont("helvetica", "bold");
  doc.text("Services Performed", 15, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  parsedServices.forEach((svc, idx) => {
    doc.setFont("helvetica", "bold");
    doc.text(`• ${svc.serviceType.value || "Service"}`, 20, y);
    doc.setFont("helvetica", "normal");
    if (!svc.items.length) {
      doc.text("No items listed.", 30, y + 6);
      y += 12;
      return;
    }
    // Table header
    y += 5;
    doc.setFontSize(9);
    doc.text("Name", 30, y);
    doc.text("Qty", 90, y);
    doc.text("Price", 110, y);
    doc.text("Subtotal", 140, y);
    doc.setLineWidth(0.1);
    doc.line(30, y + 2, 180, y + 2);

    y += 7;
    svc.items.forEach(item => {
      if (y > 260) {
        doc.addPage(); y = 20;
      }
      doc.setFontSize(9);
      doc.text(item.name || "-", 30, y);
      doc.text(String(item.quantity || "-"), 90, y);
      doc.text(formatCurrency(Number(item.price)), 110, y);
      doc.text(formatCurrency(Number(item.price) * Number(item.quantity)), 140, y);
      y += 6;
    });
    y += 4;
  });

  // Cost summary
  y += 5;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Cost Summary", 15, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Calculated Total:", 18, y);
  doc.text(formatCurrency(totalCost), 50, y);

  // Detail summary
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Other Details", 15, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text("Mileage:", 18, y);
  doc.text(service.mileage != null ? String(service.mileage) : "—", 50, y);

  if (nextOilChangeMileage) {
    y += 6;
    doc.text("Next Oil Change Mileage:", 18, y);
    doc.text(nextOilChangeMileage, 60, y);
  }

  if (typeof service.labor_hours === "number") {
    y += 6;
    doc.text("Labor Hours:", 18, y);
    doc.text(String(service.labor_hours), 50, y);
  }

  // Description
  if (service.description) {
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Description", 15, y);
    y += 7;
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(service.description, 170);
    doc.text(lines, 18, y);
    y += lines.length * 5;
  }

  // Technician notes
  if (plainNotes) {
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Technician Notes", 15, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const notesLines = doc.splitTextToSize(plainNotes, 170);
    doc.text(notesLines, 18, y);
    y += notesLines.length * 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text("Generated by Workshop Management System", 15, 287);
  doc.text(new Date().toLocaleString(), 150, 287);

  // Save
  const fileName = `ServiceRecord-${service.id || "Record"}.pdf`;
  doc.save(fileName);
}
