// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkstdutebohloapdyznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrc3RkdXRlYm9obG9hcGR5em5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjIzNDAsImV4cCI6MjA2NDczODM0MH0.r-ebm4TvDD-wVCNczdyaPxE-lv3EPjjT3Sq09FQnFww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);